// Generated by apply-spec.mjs — single source of truth for all portal copy.
export interface LoginStat { value: string; label: string; }
export const CONTENT = {
  "company": "HP",
  "aiName": "Ask HP AI",
  "website": "https://www.hp.com/",
  "loginTitleHtml": "Transform IT from<br />infrastructure to impact.",
  "loginSubtitle": "Your AI-powered analytics portal for HP data — live dashboards, regional insights, and natural language answers on your products and markets. Powered by ThoughtSpot.",
  "loginStats": [
    {
      "value": "190+",
      "label": "Countries Served"
    },
    {
      "value": "55M+",
      "label": "Customers Worldwide"
    },
    {
      "value": "Real-time",
      "label": "Analytics"
    }
  ],
  "loginCardSubtitle": "Sign in with your ThoughtSpot credentials",
  "loginDemoNoteHtml": "<strong>Sign in</strong> with your ThoughtSpot username &amp; password for <code>{host}</code>. This origin must be CORS-allowlisted on that cluster for the embeds to load.",
  "platformNav": [
    "Products",
    "Solutions",
    "Support"
  ],
  "tabs": {
    "myReports": "My Reports",
    "analytics": "Analytics",
    "inline": "Insights",
    "action": "Workflow",
    "ask": "Ask HP AI",
    "spotter": "Spotter"
  },
  "analyticsSubtitle": "Live dashboards for HP product performance, regional trends, and market data.",
  "spotterSubtitle": "Ask natural language questions about HP product and regional data.",
  "inline": {
    "subtitleReady": "Product metrics — select a product to view its performance insights",
    "subtitleIdle": "Product performance across your portfolio",
    "loading": "Loading products…",
    "errorTitle": "Couldn't load products",
    "errorMsg": "Unable to load product data.",
    "moreLabel": "View insights",
    "hideLabel": "Hide insights"
  },
  "filters": {
    "primaryLabel": "Product",
    "secondaryLabel": "Region"
  },
  "sampleQuestions": [
    "Revenue by product",
    "Sales by region",
    "Top products this quarter",
    "Performance by region over time"
  ],
  "askWelcome": "Ask me anything about HP — product performance, regional trends, market analytics — or ask about your own data and I'll chart it live.",
  "askEmptySub": "Ask any analytical question about HP products, regions, and market performance. Answers come straight from your live data with an interactive chart you can drill into.",
  "action": {
    "label": "HP Action",
    "subtitlePrefix": "Product analytics. Right-click a row and choose",
    "subtitleSuffix": "to take action on the selected item.",
    "modalTitle": "HP Action",
    "modalLead": "Pre-filled for the selected item.",
    "submitLabel": "Submit",
    "successTitle": "Action submitted"
  },
  "chatbot": {
    "welcome": "Hi! I'm Ask HP AI. Ask me about HP products, regional performance, or your analytics data.",
    "overview": "HP is a global technology company offering personal computers, printers, and software solutions for consumers and businesses. This analytics portal provides insights into product performance, regional trends, and market data powered by ThoughtSpot.",
    "greetingExample": "revenue by product",
    "examples": [
      "top products by sales",
      "performance by region"
    ]
  },
  "trialQuestionTrigger": 3,
  "upgradeReason": "Upgrade to HP Instant Insights Premium to unlock AI-powered insights, drill-down, and data exports.",
  "analyticsKeywords": [
    "product",
    "region",
    "sales",
    "revenue",
    "performance",
    "market",
    "analytics",
    "trend",
    "quarter",
    "data"
  ]
} as const;
export type Content = typeof CONTENT;
